from .content import *
from .course_syllabus import *
from .details import *
from .file import *
from .grade_determination import *
from .listing import *
from .schedule import *
from .table import *
from .video import *
